include current-theme.conf

window_margin_width 2 8

scrollback_lines 10000
wheel_scroll_multiplier 3

font_size 11
font_family Zed Sans

cursor_shape underline
cursor_blink yes

confirm_os_window_close 0

paste_actions no-op

map ctrl+v paste_from_clipboard
map ctrl+c copy_or_interrupt
